openapi: 3.0.1
info:
  title: Example API
  version: 1.0.0

tags:
  - name: article
    description: 'Everything concerning articles, comments'
  - name: user
    description: Operations about user
paths: 
  /article:
    get:
      tags:
        - article
      summary: Get all articles
      operationId: getArticles
      parameters:
        - in: query
          name: category
          schema:
            type: string
            default: BLOG
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: language
          schema:
            type: string
            default: en
        - in: query
          name: page
          schema:
            type: integer
            default: 0
        - in: query
          name: itemsPerPage
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Articles retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
    post:
      tags:
        - article
      summary: Add an article
      operationId: addArticle
      requestBody:
        description: Article object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
        required: true
      responses:
        '200':
          description: Article created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          description: Invalid object supplied
          content: {}
  '/article/{id}':
    put:
      tags:
        - article
      summary: Modify an article
      operationId: updateArticle
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      requestBody:
        description: Article that is updated
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                author:
                  $ref: '#/components/schemas/User'
                category:
                  type: string
                title:
                  type: string
                slug:
                  type: string
                text:
                  type: string
                tags:
                  type: string
                language:
                  type: string
                audience:
                  type: string
                publishDate:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Article updated
          content:
            application/json:
              schema:
                $ref: '#/paths/~1regular-user~1article~1%7Bid%7D/put/requestBody/content/application~1json/schema'
        '400':
          description: Invalid object supplied
        '404':
          description: Article not found
    delete:
      tags:
        - article
      summary: Delete an article
      operationId: deleteArticle
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: Article deleted
        '404':
          description: Article not found
  
  /user:
    get:
      tags:
        - user
      summary: Get all users
      operationId: getUsers
      parameters:
        - in: query
          name: lodge
          schema:
            type: integer
            format: int64
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 0
        - in: query
          name: itemsPerPage
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Retrieved users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - user
      summary: Add user
      operationId: addUser
      requestBody:
        description: User to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid object supplied

  /user/{id}:
    put:
      tags:
        - user
      summary: Modify a user
      operationId: updateUser
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      requestBody:
        description: User that is updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid object supplied
        '404':
          description: User not found

    delete:
      tags:
        - user
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        author:
          $ref: '#/components/schemas/User'
        category:
          type: string
        title:
          type: string
        slug:
          type: string
        text:
          type: string
        tags:
          type: string
        language:
          type: string
        audience:
          type: string
        publishDate:
          type: string
          format: date-time
   
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        birthdate:
          type: string
          format: date-time
        userStatus:
          type: string